name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: LockIn.sln
      Project_Path: LockIn/LockIn.csproj
      Publish_Path: ${{ github.workspace }}/publish
      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore the solution
      run: dotnet restore ${{ env.Project_Path }} /p:EnableWindowsTargeting=true

    - name: Build the solution
      run: dotnet build ${{ env.Project_Path }}
         --configuration ${{ matrix.configuration }}
         --no-restore
         --runtime win-x64
         /p:EnableWindowsTargeting=true
         /p:SelfContained=true

    - name: Publish
      run: dotnet publish ${{ env.Project_Path }}
        --configuration ${{ matrix.configuration }}
        --no-restore
        --no-build
        --runtime win-x64
        --property:PublishDir=${{ env.Publish_Path }}
        /p:EnableWindowsTargeting=true
        /p:SelfContained=true

   
    # Upload the artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x64
        path: ${{ env.Publish_Path }}
