name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: LockIn.sln
      Project_Path: LockIn/LockIn.csproj
      Publish_Path: Output/
      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore the solution
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build the solution
      run: dotnet build ${{ env.Solution_Name }}
         --configuration ${{ matrix.configuration }}
         --no-restore

    - name: Publish
      run: dotnet publish ${{ env.Project_Name }}
        --configuration ${{ matrix.configuration }}
        --no-restore
        --no-build
        --property:PublishDir=${{ env.PUBLISH_DIR }}

   
    # Upload the artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x64
        path: ${{ env.Output_Path }}
